### ISSUE TITLE
Cant Add Stardew Valley Expanded

### ISSUE THREAD

**Issue by AkumaNoYami** [printfuck/stardew-multiplayer-docker#17]
at first i am New at Git so sorry when i am in the wrong section 

I add the Mods in Env 
Enable_STARDEW_VALLEY_EXPANDED_MOD True 
But it doesnt show ingame 

the Other Mods ive Add work

**Comment by printfuck** [comment]
Configuring mods only works for the few, that are in the `docker/mods` folder and at the moment I don't have the time for adding more.

If you like to improve on that, you can fork this project and add it yourself - or look through the already existing forks to find out, if somebody already did that.

I'm sorry for reacting this late to your issue.

**Comment by HumanoidSandvichDispenser** [comment]
If you or anyone else is still wondering, the correct env variable to enable SVE would be `ENABLE_STARDEWVALLEYEXPANDED_MOD=true`. But if you try running it, the SpaceCore mod will crash because it can't find an audio output device, which can be fixed by installing PulseAudio and creating a sink. It also requires SMAPI version >= 3.15, whereas SMAPI here is 3.14.7.

So I made [a fork](https://github.com/HumanoidSandvichDispenser/sve-multiplayer-docker) that fixes these issues.
