### ISSUE TITLE
Docker not starting? 

### ISSUE THREAD

**Issue by LOGICHACK** [printfuck/stardew-multiplayer-docker#19]
Im new to docker things so it is most likely my issue, but I keep getting this error everytime I try to start the server, I'm using unraid if that's any help I can vnc and webui into it just fine but this pops up am I missing my steam creds somewhere or something else like that?

![image](https://user-images.githubusercontent.com/100243124/194529979-abce1372-15c9-4eba-b4b8-5b571def66e7.png)

**Comment by printfuck** [comment]
Sorry for the late response. There could be several causes for your issue

Are you running it as a "stack" from the docker-compose example? If not, you probably should try that next.

Although mono should be cross platform compatible, there might be issues with running this container on arm32/64.

**Comment by LOGICHACK** [comment]
Sorry about the late reply, as I'm very new to docker I am unsure what that means. I pulled an image from the docker hub which linked me back here. I was deploying it via unraid which set it up automatically I am currently attempting to use portainer to set it up as a "stack" granted I have no idea what that means and my google-fu isn't what it use to be

**Comment by printfuck** [comment]
Well, up to now, I didn't even know people uploaded images of this project to docker hub ^^

Since I can't actually see, what they are doing and how they potentially modified the project, I am sorry to say, that I can't offer any help or support for this way of deployment.

But in portainer you can also import this project via `stacks` from a `git`-source. I've never done this - and I may never will, since I'm not a fan of portainer, but if I had to do it, I'd go that route.
