### ISSUE TITLE
Option to pause the server while no one is playing

### ISSUE THREAD

**Issue by fredmnl** [printfuck/stardew-multiplayer-docker#8]
Hey, love your work! I just got my server started and I was wondering if we could pause it when no one is inside. It might be a stupid idea, I have not been playing the game at all yet but at first glance I feel like having the time pass by while not playing is not desirable. 

I was thinking of using a `docker pause` type command when the server sees that there are no local players which is actually easily accessible in the logs. There would need to be some kind of UI to unpause it when someone wants to log in again. I'm thinking of a second container for that UI and I'm still looking for the best way to enable it to pause/unpause the other container without giving it too much rights (e.g. the complete docker socket).

Any thoughts on the overall idea and implementation?

**Comment by printfuck** [comment]
That is a nice idea. First of all: with the "Always on" Mod (Hit F9 after startup) the game should automatically pause, once everybody left, so that no time will pass ingame, when nobody is logged in.

A web control interface for controlling the container could be easily achieved by shared paths, which contain state files or pipes, to transmit start or stop signals. Triggering this by incoming tcp or udp connections would be the admirable goal here.

I personally still hope for a dedicated server made by the author, or at least a mod, that removes the graphical interface from the game, since since this is the next best thing when it comes to saving load. I dabbled with doing it myself, since editing unobscured C# is pretty easy, but got carried away.

Feel free to fork and improve.
